# Generated by Django 2.2.1 on 2019-06-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
