# Generated by Django 2.2.1 on 2019-06-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('wallet_adress', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_state',
            field=models.IntegerField(default=0),
        ),
    ]
