# Generated by Django 2.2.1 on 2019-06-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190609_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='contract_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_adress',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
