# Generated by Django 2.2.1 on 2019-06-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190609_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contract_adress',
            field=models.CharField(default='', max_length=200),
        ),
    ]
